### ISSUE TITLE
Project.py error

### ISSUE THREAD

**Issue by gwenwhite** [cmelab/Advanced-Sampling#44]
When trying to run jobs, project.py produces this error below:

`Traceback (most recent call last):
  File "/home/gwenwhite/miniconda3/envs/advsamp/lib/python3.10/site-packages/signac/contrib/project.py", line 2297, in init_project
    assert project.id == str(name)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gwenwhite/cmelab/repos/Advanced-Sampling/MCMC/MCMC-flow/init.py", line 88, in <module>
    main()
  File "/home/gwenwhite/cmelab/repos/Advanced-Sampling/MCMC/MCMC-flow/init.py", line 53, in main
    project = signac.init_project("MCMC-project")  # Set the signac project name
  File "/home/gwenwhite/miniconda3/envs/advsamp/lib/python3.10/site-packages/signac/contrib/project.py", line 3024, in init_project
    return Project.init_project(
  File "/home/gwenwhite/miniconda3/envs/advsamp/lib/python3.10/site-packages/signac/contrib/project.py", line 2304, in init_project
    raise RuntimeError(
RuntimeError: Failed to initialize project 'MCMC-project'. Path '/home/gwenwhite/cmelab/repos/Advanced-Sampling/MCMC/MCMC-flow' already contains a conflicting project configuration.
(advsamp) [gwenwhite@fry MCMC-flow]$ python project.py submit
Traceback (most recent call last):
  File "/home/gwenwhite/cmelab/repos/Advanced-Sampling/MCMC/MCMC-flow/project.py", line 23, in <module>
    from simulation import Simulation
  File "/home/gwenwhite/cmelab/repos/Advanced-Sampling/MCMC/simulation.py", line 11, in <module>
    from MCMC.utils import pair_distances, check_overlap
ModuleNotFoundError: No module named 'MCMC'
`

**Comment by marjanalbooyeh** [comment]
`RuntimeError: Failed to initialize project 'MCMC-project'. Path '/home/gwenwhite/cmelab/repos/Advanced-Sampling/MCMC/MCMC-flow' already contains a conflicting project configuration.`

Looks like this code is trying to initiate a signac project in a directory that already has a project named MCMC-project. 
If you want to start a completely new signac project, you can try one of these:
1- Clone the repo in a new directory and run your code in the new directory.
2- Get a backup of previous signac files (mainly the workspace directory and files generated by signac) and delete them. Now if you run `python init.py` it recreates the file. But make sure you copy your files before deleting them in case you wanna check your previous runs.

**Comment by gwenwhite** [comment]
Oh I see. So if I am trying to test post equilibrium functions on jobs, will I need to create an entirely new job everytime? Basically just trying to make sure an rdf is created with the code I added in project.py.

**Comment by marjanalbooyeh** [comment]
No for post-run operations we shouldn't be needing to create new jobs. Let's see what is causing that error you're getting. If you are around, we can meet on Zoom or Slack to troubleshoot. It might be a package import problem.
